### ISSUE TITLE
2 links language 'POWERED_BY' on copyright (footer)

### ISSUE THREAD

**Issue by phpbb-es** [phpBB-Studio/AdminDashboard#3]
**Describe the bug**
Hello,

I see two links for copyright line...

**To Reproduce**
1. Go to ACP
2. Scroll down to '....'
3. See error

**Screenshots**
![phpBB Spain](https://www.phpbb-es.com/archivos/acp.png) 

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit
 - Browser: Firefox
 - Version: 74.0.1 (64-Bit)

**Comment by mrgoldy** [comment]
Ah yes, we tried to be sneaky with applying a copyright, but did not think about multiple languages.
Thanks for letting us know.

**Comment by mrgoldy** [comment]
This will be fixed in the next release.
Once again thank you for reporting it.

**Comment by 3D-I** [comment]
Closed and fixed with https://github.com/phpBB-Studio/AdminDashboard/commit/de70000db6756301bb4cb8d9b1664d2d15d19756#diff-303d825a4451c86deed9f3125160b7dc
