### ISSUE TITLE
Enhance and therefore improve the usability of the Group Permissions screen

### ISSUE THREAD

**Issue by nomind60s** [phpBB-Studio/AdminDashboard#4]
The Group Permissions area can be frustrating because there are too many dropdown menus and unused screen space IMHO.

The usability of the **mode=setting_group_global** page could be greatly increased by eliminating the dropdown box of three choices and just displaying the User permissions, Global Moderator permissions and Administrative permissions in separate sections of the page.

It takes three mouse clicks to see and manage the roles for a group. Having them accessible on one page would simplify things IMHO.

For comparison, look at how **mode=setting_group_local** operates for multiple forums. The single page makes it far easily to manage.

Maybe even more helpful is some method to display something like this (built from database queries into Excel):
![Screenshot 2022-03-03 090924](https://user-images.githubusercontent.com/25851756/157505800-ba4256cc-392c-408a-bc0e-a1ce998c72a6.jpg)

Thanks for your consideration and for this very useful tool.

**Comment by 3D-I** [comment]
I think you have confused what this extension does and how it is structured. Yours is an idea that should be posted elsewhere.
